version: "3.7"
services:
  mongo_db:
    container_name: local-mongo-421
    image: mongo:4.2.0-bionic
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27018"
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3007:3007"
    environment:
      PORT: 3007
      DB_URL: mongodb://mongo_db:27018/socialmedia
      TWILIO_ACCOUNT_SID: AC0ab09c240edf73497cc17a200af31d6a
      TWILIO_AUTH_TOKEN: 5eba6d3874af1d1f7e79b1ab49f85704
    depends_on:
      - mongo_db
    links:
      - "mongo_db"

volumes:
  mongo_db: {}
